config/routes.rb
Rails.application.routes.draw do
  get 'welcom/index'

  resources :articles do
  	resources :comments
end
  root 'welcom#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_many :comments
validates :nama, presence: true, length:{minimum: 5}

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "rahasia", except: [:index, :show]
	
	def index
		@articles = Article.all.order('nama ASC')
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new

	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		
		@article = Article.new(article_params)
 
	  if @article.save
	  redirect_to @article
	  else 
		render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end
end

	private
	
	def article_params
		params.require(:article).permit(:nama, :email, :telp, :alamat)
	end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
def create
    @article = Article.find(params[:article_id])
	@comment = @article.comments.create(comment_params)
	redirect_to article_path(@article)

end

private
def comment_params
	params.require(:comment).permit(:commenter, :body)

	end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/articles/_form.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
	<p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
	

<p>
	<%= form.label :nama %><br>
	<%= form.text_field :nama %>
</p>

<p>
	<%= form.label :email %><br>
	<%= form.text_field :email %>
</p>

<p>
	<%= form.label :telp %><br>
	<%= form.text_field :telp %>
</p>

<p>
	<%= form.label :alamat %><br>
	<%= form.text_field :alamat %>
</p>

<p>
	<%= form.submit %>
</p>

<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/edit.html.erb
<<h1>Edit article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
	<%= form.label :nama %><br>
	<%= form.text_field :nama %>
</p>

<p>
	<%= form.label :email %><br>
	<%= form.text_field :email %>
</p>

<p>
	<%= form.label :telp %><br>
	<%= form.text_field :telp %>
</p>

<p>
	<%= form.label :alamat %><br>
	<%= form.text_field :alamat %>
</p>

<p>
	<%= form.submit %>
</p>

<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/index.html.erb
<h1 class="suastra"<center>Suastra Emergency</center></h1>


<%= link_to 'Absen Dulu ', new_article_path%>
<a class="btn btn-primary" href="/articles/new" role="button">Absen</a><br><br>


<div class="row">
		<div class="col-md-6 col-sm-6">


			<table class="table table-responsive">
				<tr>
				<th>no</th>	
				<th>nama</th>
				<th>email</th>
				<th>telp</th>
				<th>alamat</th>
				<th>Action</th>
				</tr>

				<% @articles.each_with_index do |article, i| %>
					 <tr>
					 	<td><%= i+1 %></td>
						<td><%= article.nama %></td>
						<td><%= article.email %></td>
						<td><%= article.telp %></td>
						<td><%= article.alamat %></td>
						<td><%= link_to 'show', articles_path(article) %></td>
						<td><%= link_to 'edit', edit_article_path(article) %></td>
						<td><%= link_to 'destroy', article_path(article), method: :delete,
							data: { confirm: 'apa kamu yakin'} %></td>
					</tr>
				<% end %>
			</table>
		</div>
	<div class="col-md-6 col-sm-6">
			<%= image_tag("yugcy.jpeg", class: "img.fluid img.responsive")%>
					
	<html>
<head>
<style> 
body {
	background-color:lightgrey;
}
</style>
</head>
<body>	
				
	</div>
</div>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
	
	<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
	<%= form.label :nama %><br>
	<%= form.text_field :nama %>
</p>

<p>
	<%= form.label :email %><br>
	<%= form.text_field :email %>
</p>

<p>
	<%= form.label :telp %><br>
	<%= form.text_field :telp %>
</p>

<p>
	<%= form.label :alamat %><br>
	<%= form.text_field :alamat %>
</p>

<p>
	<%= form.submit %>
</p>

<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>nama:<strong>
	<%= @article.nama %>
</p>

<p>
	<strong>email:<strong>
	<%= @article.email %>
</p>

<p> 
	<strong>No telp:<strong>
	<%= @article.telp %>
</p>

<p>
	<strong>alamat:<strong>
	<%= @article.alamat %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>

	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>

	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>
<% end %>


<h2>Add a comment:</h2>
<%= form_with(model: [@article, @article.comments.build ], local: true) do |form| %>

	<p>
		<%= form.label :commenter %><br>
		<%= form.text_field :commenter %>
	</p>
 
	<p>
		<%= form.label :body %><br>
		<%= form.text_area :body %>
	</p>

	<p>
		<%= form.submit %>
	</p>	
	<% end %> 

<%= link_to 'edit', articles_path(@article) %>
<%= link_to 'back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jajan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/welcom/index.html.erb
<h1>hay suastra</h1>
<%= link_to 'my blog', controller: 'articles' %>

<!DOCTYPE html>
<html>
<head>

<style> 
p {
	text-align: center;
	color: red;
}

</style>	
</head>
<body>

<p>Superman Is Dead</p>


<p id="para1">Outsiders</p>


<p>Lady rose</p>	



</body>
</html>

<html>
<head>
<style> 
body {
	background-color:black;
}

p {
	font-family:  verdana;
	font-size: 20px;
}
	
</style>
</head>
<body>	

<html>
<head>
<style>


p.double {border-style: double;
border-color: red;}
p.groove {border-style: groove;
border-color: blue;}

</style>
</head>
<body>

<h2>Daftar lagu</h2>
<p>Superman Is Dead:</p>

<p class="double">A double border.</p>
<p class="groove">A groove border.</p>

</body>
</html>


</body>
</html>